### ISSUE TITLE
gocql breaking change for ParseConsistency

### ISSUE THREAD

**Issue by ollelindeman** [db-journey/cassandra-driver#1]
Function signature for ParseConsistency changed in the following pull-request:
https://github.com/gocql/gocql/pull/983/files#diff-38a0fa12b0c511105c3a411f0df3e318R230

```
cassandra.go:191: multiple-value gocql.ParseConsistency() in single-value context
```

An easy fix could be to use `MustParseConsistency` instead, but unsure if this issue should be in this repo or at gocql.

**Comment by gravis** [comment]
We should definitely use `ParseConsistency`, as `MustParseConsistency` would panic in case of an error. That's the responsibility of the caller to panic or handle the error. Could you provide a pull request for that please?

Thanks

**Comment by zvickery** [comment]
It seems like this change is now causing the below error:

`/go/src/github.com/db-journey/cassandra-driver/cassandra.go:45: assignment count mismatch: 2 = 1`

**Comment by gravis** [comment]
@zvickery can you try again after a `go get -u` please?

**Comment by zvickery** [comment]
My mistake, things are working now.  Thank you!
